/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary": "#ffffff",
        "on-surface-variant": "#404a3b",
        "on-primary-fixed-variant": "#005300",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#002200",
        "on-tertiary-container": "#ffb9d4",
        "secondary": "#bc0100",
        "surface-bright": "#f9f9f9",
        "tertiary-fixed": "#ffd9e5",
        "surface-dim": "#dadada",
        "error": "#ba1a1a",
        "on-secondary-fixed-variant": "#930000",
        "on-secondary-fixed": "#410000",
        "on-error-container": "#93000a",
        "surface-tint": "#106e09",
        "surface-container": "#eeeeee",
        "surface-container-low": "#f3f3f3",
        "outline": "#707a6a",
        "on-primary": "#ffffff",
        "on-tertiary-fixed": "#3d0023",
        "inverse-surface": "#2f3131",
        "primary-fixed": "#9cf987",
        "on-secondary-container": "#fffbff",
        "surface": "#f9f9f9",
        "primary-fixed-dim": "#81db6e",
        "inverse-on-surface": "#f1f1f1",
        "secondary-fixed-dim": "#ffb4a8",
        "on-background": "#1a1c1c",
        "secondary-fixed": "#ffdad4",
        "background": "#f9f9f9",
        "tertiary-container": "#9a2a64",
        "on-tertiary-fixed-variant": "#851753",
        "on-surface": "#1a1c1c",
        "tertiary-fixed-dim": "#ffb0cf",
        "primary-container": "#006600",
        "secondary-container": "#e1291a",
        "inverse-primary": "#81db6e",
        "primary": "#004b00",
        "on-tertiary": "#ffffff",
        "outline-variant": "#bfcab7",
        "tertiary": "#7b0d4c",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "surface-container-high": "#e8e8e8",
        "surface-container-highest": "#e2e2e2",
        "surface-variant": "#e2e2e2",
        "on-primary-container": "#88e274"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      }, maxWidth: {
        "container-max-width": "1200px",
      },
      spacing: {
        "margin-desktop": "40px",
        "stack-md": "16px",
        "gutter": "24px",
        "stack-lg": "32px",
        "margin-mobile": "16px",
        "base": "8px",
        "stack-sm": "8px",
        // removed container-max-width from here
      },
      fontFamily: {
        "headline-lg-mobile": ["Montserrat"],
        "body-md": ["Inter"],
        "label-md": ["Inter"],
        "headline-lg": ["Montserrat"],
        "headline-xl": ["Montserrat"],
        "headline-md": ["Montserrat"],
        "caption": ["Inter"],
        "body-lg": ["Inter"]
      },
      fontSize: {
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "caption": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}